USE test;
GRANT ALL PRIVILEGES ON *.* TO 'test';
GRANT GRANT OPTION ON *.* TO 'test';
DROP USER IF EXISTS 'connector'@'%';
CREATE USER 'connector'@'%' IDENTIFIED BY 'abcde';
GRANT SELECT, INSERT, UPDATE, DELETE ON test.* TO 'connector'@'%';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    userid BIGINT NOT NULL AUTO_INCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email VARCHAR(512) UNIQUE NOT NULL,
    pass VARCHAR(512) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (userid)
);